Restore hidraw.pyx
Otherwise, when using --with-libusb, hid.c is only generated once for
LibUSB, and later reused for HIDRAW.

This causes PyInit_hidraw to be missing in the generated .so for HIDRAW.

>>> import hidraw
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: dynamic module does not define module export function (PyInit_hidraw)